from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Any

from .config import SAFETY_BOUNDARY
from .importer import import_now
from .live_readiness import build_live_readiness
from .state_store import list_paper_observation_logs, now_iso


CONTROL_CONSOLE_VERSION = "V13.7.36"
CONTROL_CONSOLE_SOURCE = "alphapilot_control_console_v13_7_36"
BEIJING_TZ = timezone(timedelta(hours=8), name="Asia/Shanghai")


def _safe_float(value: Any, fallback: float = 0.0) -> float:
    try:
        if value is None:
            return fallback
        return float(value)
    except (TypeError, ValueError):
        return fallback


def _parse_outcome_r(log: dict[str, Any]) -> float | None:
    if log.get("outcomeR") is not None:
        return _safe_float(log.get("outcomeR"))
    outcome = str(log.get("outcome") or "").strip().upper().replace("R", "")
    if not outcome:
        return None
    return _safe_float(outcome, fallback=0.0)


def _is_manual_forward_log(log: dict[str, Any]) -> bool:
    if log.get("autoGenerated"):
        return False
    sandbox_mode = str(log.get("sandboxMode") or "").lower()
    if "historical" in sandbox_mode or "virtual" in sandbox_mode:
        return False
    return True


def _summarize_logs(logs: list[dict[str, Any]]) -> dict[str, Any]:
    manual_logs = [log for log in logs if _is_manual_forward_log(log)]
    virtual_logs = [log for log in logs if not _is_manual_forward_log(log)]
    closed_logs = [log for log in logs if _parse_outcome_r(log) is not None]
    manual_closed_logs = [log for log in manual_logs if _parse_outcome_r(log) is not None]
    rule_matched_logs = [log for log in logs if log.get("ruleMatched") or log.get("logType") == "rule_matched"]
    risk_logs = [log for log in logs if log.get("logType") == "risk_warning"]
    invalidated_logs = [log for log in logs if log.get("logType") == "invalidated"]
    outcome_r_values = [_parse_outcome_r(log) for log in closed_logs]
    outcome_r_values = [value for value in outcome_r_values if value is not None]
    latest = max(logs, key=lambda item: str(item.get("createdAt") or ""), default={})
    return {
        "totalLogCount": len(logs),
        "manualForwardLogCount": len(manual_logs),
        "virtualReplayLogCount": len(virtual_logs),
        "closedSampleCount": len(closed_logs),
        "manualClosedSampleCount": len(manual_closed_logs),
        "ruleMatchedCount": len(rule_matched_logs),
        "riskWarningCount": len(risk_logs),
        "invalidatedCount": len(invalidated_logs),
        "outcomeRTotal": round(sum(outcome_r_values), 4),
        "latestLogAt": latest.get("createdAt"),
        "latestPair": latest.get("pair"),
        "latestOutcome": latest.get("outcome"),
        "latestSource": latest.get("source"),
    }


def _row_gate(readiness_row: dict[str, Any], log_summary: dict[str, Any]) -> tuple[str, str, str, list[str]]:
    blockers: list[str] = []
    if log_summary["manualForwardLogCount"] < 3:
        blockers.append(f"真实前向日志不足：{log_summary['manualForwardLogCount']}/3")
    if log_summary["manualClosedSampleCount"] < 1:
        blockers.append(f"真实前向闭合样本不足：{log_summary['manualClosedSampleCount']}/1")
    if log_summary["ruleMatchedCount"] < 1:
        blockers.append("尚无规则匹配记录")
    if log_summary["riskWarningCount"] > 0 or log_summary["invalidatedCount"] > 0:
        blockers.append("存在风险提醒或条件失效记录")
    if not readiness_row.get("manualTicketAllowed"):
        blockers.extend(str(item) for item in readiness_row.get("blockers") or [])

    if any(("风险" in item or "失效" in item or "回撤过高" in item) for item in blockers):
        return "blocked_for_review", "先暂停复核", "danger", blockers
    if blockers:
        return "needs_forward_data", "等待前向数据", "warn", blockers
    return "ready_for_manual_review", "可进入人工复核", "ok", blockers


def _build_candidate_expansion(payload: dict[str, Any], active_task_ids: set[str]) -> dict[str, Any]:
    queue = payload.get("strategyCandidateQueue") if isinstance(payload.get("strategyCandidateQueue"), dict) else {}
    summary = queue.get("summary") if isinstance(queue.get("summary"), dict) else {}
    candidates = queue.get("candidates") if isinstance(queue.get("candidates"), list) else []
    expansion_candidates: list[dict[str, Any]] = []
    for item in candidates:
        if not isinstance(item, dict):
            continue
        artifact_id = str(item.get("artifactId") or "")
        if artifact_id in active_task_ids:
            continue
        queue_type = str(item.get("queueType") or "")
        if queue_type not in {"priority_forward_validation", "research_watchlist", "ml_evaluation"}:
            continue
        expansion_candidates.append({
            "artifactId": artifact_id,
            "strategyId": item.get("strategyId"),
            "title": item.get("title"),
            "queueType": item.get("queueType"),
            "queueLabel": item.get("queueLabel"),
            "priorityScore": item.get("priorityScore"),
            "sampleCount": item.get("sampleCount"),
            "winRatePct": item.get("winRatePct"),
            "profitFactor": item.get("profitFactor"),
            "rewardRiskRatio": item.get("rewardRiskRatio"),
            "maxDrawdownPct": item.get("maxDrawdownPct"),
            "nextAction": item.get("nextAction"),
            "safetyNote": "候选扩展只进入研究队列，不会创建订单或自动交易。",
        })
    return {
        "summary": {
            "totalCandidates": summary.get("totalCandidates") or len(candidates),
            "forwardReadyCount": summary.get("forwardReadyCount") or 0,
            "researchWatchlistCount": summary.get("researchWatchlistCount") or 0,
            "rejectedCount": summary.get("rejectedCount") or 0,
            "expandableCandidateCount": len(expansion_candidates),
            "topCandidateTitle": (expansion_candidates[0].get("title") if expansion_candidates else summary.get("topCandidateTitle")),
        },
        "topCandidates": expansion_candidates[:8],
        "answer": (
            "可以继续扩展候选，但必须先进入研究队列、补回测/标签/前向日志，再走同一套实盘前闸门。"
            if expansion_candidates
            else "暂未发现新的高优先级候选；先复核当前 5 条观察策略。"
        ),
    }


def build_forward_review(payload: dict[str, Any]) -> dict[str, Any]:
    readiness = build_live_readiness(payload)
    all_logs_raw = list_paper_observation_logs()
    logs_by_artifact = all_logs_raw if isinstance(all_logs_raw, dict) else {}
    rows: list[dict[str, Any]] = []
    active_task_ids: set[str] = set()
    for readiness_row in readiness.get("rows") or []:
        if not isinstance(readiness_row, dict):
            continue
        task_id = str(readiness_row.get("taskId") or "")
        active_task_ids.add(task_id)
        logs = logs_by_artifact.get(task_id) if isinstance(logs_by_artifact.get(task_id), list) else []
        safe_logs = [log for log in logs if isinstance(log, dict)]
        log_summary = _summarize_logs(safe_logs)
        review_status, review_label, tone, blockers = _row_gate(readiness_row, log_summary)
        rows.append({
            "taskId": task_id,
            "strategyId": readiness_row.get("strategyId"),
            "title": readiness_row.get("title"),
            "timeframe": readiness_row.get("timeframe"),
            "readinessStatus": readiness_row.get("status"),
            "readinessScore": readiness_row.get("readinessScore"),
            "reviewStatus": review_status,
            "reviewLabel": review_label,
            "tone": tone,
            "logSummary": log_summary,
            "blockers": blockers[:10],
            "latestLogs": safe_logs[-5:][::-1],
            "recommendedPairs": readiness_row.get("recommendedPairs") or [],
            "nextAction": (
                "准备人工复核材料；票据仍只是本地记录，不连接交易所。"
                if review_status == "ready_for_manual_review"
                else "继续收集真实前向日志、规则匹配、闭合样本和风险失效记录。"
            ),
        })
    rows.sort(key=lambda item: (item["reviewStatus"] != "ready_for_manual_review", item["reviewStatus"] == "blocked_for_review", -_safe_float(item.get("readinessScore"))))

    total_manual_logs = sum(row["logSummary"]["manualForwardLogCount"] for row in rows)
    total_virtual_logs = sum(row["logSummary"]["virtualReplayLogCount"] for row in rows)
    total_manual_closed = sum(row["logSummary"]["manualClosedSampleCount"] for row in rows)
    total_rule_matches = sum(row["logSummary"]["ruleMatchedCount"] for row in rows)
    ready_rows = sum(1 for row in rows if row["reviewStatus"] == "ready_for_manual_review")
    blocked_rows = sum(1 for row in rows if row["reviewStatus"] == "blocked_for_review")
    candidate_expansion = _build_candidate_expansion(payload, active_task_ids)

    return {
        "version": CONTROL_CONSOLE_VERSION,
        "generatedAt": now_iso(),
        "source": CONTROL_CONSOLE_SOURCE,
        "reviewDate": readiness.get("reviewDate"),
        "reviewDateLabel": readiness.get("reviewDateLabel"),
        "daysUntilReview": readiness.get("daysUntilReview"),
        "summary": {
            "candidateCount": len(rows),
            "readyForManualReviewCount": ready_rows,
            "blockedForReviewCount": blocked_rows,
            "needsForwardDataCount": len(rows) - ready_rows - blocked_rows,
            "manualForwardLogCount": total_manual_logs,
            "virtualReplayLogCount": total_virtual_logs,
            "manualClosedSampleCount": total_manual_closed,
            "ruleMatchedCount": total_rule_matches,
            "nextAction": (
                "7月10日前先补真实前向观察日志；当前本地虚拟样本只能辅助复盘，不能替代真实前向样本。"
                if (readiness.get("daysUntilReview") or 0) > 0
                else "复核窗口已到：先查看每条策略的真实前向日志、闭合样本和风险记录。"
            ),
        },
        "rows": rows,
        "candidateExpansion": candidate_expansion,
        "safetyBoundary": {
            **SAFETY_BOUNDARY,
            "forwardReviewOnly": True,
            "candidateExpansionCreatesOrders": False,
            "manualTicketsOnly": True,
        },
        "safetyNotes": [
            "前向复核只读取本地观察和报告，不连接交易所。",
            "候选扩展只进入研究队列，不自动加入实盘。",
            "本版本不保存 API Key，不接 Trade API，不接 Withdraw API，不创建真实订单。",
        ],
    }


def refresh_forward_review() -> dict[str, Any]:
    payload = import_now()
    return build_forward_review(payload)
